// src/App.vue
<script setup>
import { ref } from 'vue'
import Agent5   from './pages/Agent5/Agent5.vue'
import Agent5v5 from './pages/Agent5v5/Agent5v5.vue'
import Map      from './pages/Map/Map.vue'

const tabs = [
  { key: 'agent5',   label: 'エージェント (5人)' },
  { key: 'agent5v5', label: '5 VS 5' },
  { key: 'map',      label: 'マップ' },
]

const activeTab = ref('agent5')
</script>

<template>
  <div class="sticky-top">
    <header class="header">
      <div>
        <div class="header__logo">VAL<span>//</span>RANDOM</div>
        <div class="header__subtitle">VALORANT ランダムピック</div>
      </div>
      <div class="header__badge">Vue 3</div>
    </header>

    <div class="tabs">
      <button
        v-for="tab in tabs"
        :key="tab.key"
        class="tab-btn"
        :class="{ 'tab-btn--active': activeTab === tab.key }"
        @click="activeTab = tab.key"
      >{{ tab.label }}</button>
    </div>
  </div>

  <main>
    <Agent5   v-show="activeTab === 'agent5'" />
    <Agent5v5 v-show="activeTab === 'agent5v5'" />
    <Map      v-show="activeTab === 'map'" />
  </main>
</template>

// valorant-react/src/App.jsx
import { useState } from 'react'
import AgentTab from './pages/AgentTab/AgentTab'
import MapTab from './pages/MapTab/MapTab'

const TABS = [
  { key: 'agent', label: 'エージェント', component: <AgentTab /> },
  { key: 'map',   label: 'マップ',       component: <MapTab /> },
]

export default function App() {
  const [activeTab, setActiveTab] = useState('agent')
  const current = TABS.find(t => t.key === activeTab)

  return (
    <>
      <header className="header">
        <div>
          <div className="header__logo">VAL<span>//</span>RANDOM</div>
          <div className="header__subtitle">VALORANT ランダムピック</div>
        </div>
        <div className="header__badge">React 18</div>
      </header>

      <div className="tabs">
        {TABS.map(tab => (
          <button
            key={tab.key}
            className={`tab-btn${activeTab === tab.key ? ' tab-btn--active' : ''}`}
            onClick={() => setActiveTab(tab.key)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <main>
        {current.component}
      </main>
    </>
  )
}
